kind: Deployment
apiVersion: apps/v1

metadata:
  name: django-notes
  namespace: dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: django-notes

  template:
    metadata:
      labels:
        app: django-notes

    spec:
      containers:
      - name: django-notes

        image: muhammadzaid673/python_note_django_app:v2

        ports:
        - containerPort: 8000